backend:
  name: github
  repo: arhill05/wedding-site

# backend:
#     name: test-repo

media_folder: src/images
public_folder: images

collections:
  - name: "Christmas List"
    label: "Christmas List Item"
    folder: "content/christmas-list"
    create: true
    identifier_field: 'name'
    fields:
      - { name: "name", label: "Name" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "link", label: "Link" }
      - { name: "person", widget: "select", options: ["Drew", "Julie"] }