backend:
  name: git-gateway
  repo: arhill05/wedding-site

# backend:
#     name: test-repo

media_folder: src/images
public_folder: images

collections:
  - name: "Christmas List"
    label: "Christmas List Item"
    folder: "content/christmas-list"
    identifier_field: "name"
    create: true
    summary: "{{person}} - {{name}}"
    editor:
      preview: false
    fields:
      - { name: "name", label: "Name" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "link", label: "Link", required: false }
      - { name: "person", widget: "select", options: ["Drew", "Julie"] }